export const CLINICAL_GUIDANCE = {
  curb65: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of mortality (1.5% for score 0, 3.2% for score 1)', recommendation: 'Consider outpatient treatment. Patients can typically be managed at home with oral antibiotics if pneumonia is confirmed.' } },
    { threshold: 3, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of mortality (13%)', recommendation: 'Consider hospital admission or close outpatient monitoring. Short inpatient observation may be appropriate.' } },
    { threshold: 6, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of mortality (${score === 3 ? '17%' : score === 4 ? '41.5%' : '57%'})`, recommendation: 'Hospital admission recommended. Consider ICU admission for scores 4-5, especially with additional risk factors.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  centor: [
    { threshold: 2, guidance: { riskCategory: 'Very Low Risk', interpretation: (score: number) => `${score <= 0 ? '1-2.5%' : '5-10%'} probability of streptococcal pharyngitis`, recommendation: 'No testing or antibiotics needed. Symptomatic treatment is appropriate. Streptococcal infection is unlikely.' } },
    { threshold: 4, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `${score === 2 ? '11-17%' : '28-35%'} probability of streptococcal pharyngitis`, recommendation: 'Rapid antigen detection test (RADT) or throat culture recommended. Treat with antibiotics if test is positive.' } },
    { threshold: 5, guidance: { riskCategory: 'High Risk', interpretation: '51-53% probability of streptococcal pharyngitis', recommendation: 'Consider empiric antibiotic treatment or perform rapid antigen detection test. High likelihood of streptococcal infection.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  wells_dvt: [
    { threshold: 1, guidance: { riskCategory: 'Low Probability', interpretation: 'Low probability of DVT (~5%)', recommendation: 'D-dimer testing recommended. If D-dimer is negative, DVT is effectively ruled out. If positive, proceed to ultrasound imaging.' } },
    { threshold: 3, guidance: { riskCategory: 'Moderate Probability', interpretation: 'Moderate probability of DVT (~17%)', recommendation: 'D-dimer testing recommended. If negative, DVT unlikely. If positive, compression ultrasound is indicated.' } },
    { threshold: 10, guidance: { riskCategory: 'High Probability', interpretation: 'High probability of DVT (~53%)', recommendation: 'Compression ultrasound imaging strongly recommended. Consider empiric anticoagulation while awaiting imaging if no contraindications.' } },
  ],
  wells_pe: [
    { threshold: 2, guidance: { riskCategory: 'Low Probability', interpretation: 'Low probability of PE (~2%)', recommendation: 'D-dimer testing recommended. If D-dimer is negative, PE is effectively ruled out. If positive, proceed to CT pulmonary angiography (CTPA).' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate Probability', interpretation: 'Moderate probability of PE (~20-30%)', recommendation: 'D-dimer or CTPA recommended depending on clinical judgment. If D-dimer positive or not performed, CTPA is indicated.' } },
    { threshold: 13, guidance: { riskCategory: 'High Probability', interpretation: 'High probability of PE (~65%)', recommendation: 'CT pulmonary angiography (CTPA) strongly recommended. Consider empiric anticoagulation if no contraindications while awaiting imaging.' } },
  ],
  heart: [
    { threshold: 4, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of major adverse cardiac events (MACE) at 6 weeks: 0.9-1.7%', recommendation: 'Early discharge with outpatient follow-up is appropriate. No further cardiac workup needed unless clinically indicated. Consider non-cardiac causes of chest pain.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of MACE at 6 weeks: 12-17%', recommendation: 'Observation with serial troponins and ECGs recommended. Stress testing or coronary CT angiography may be appropriate. Cardiology consultation should be considered.' } },
    { threshold: 11, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of MACE at 6 weeks: 50-65%', recommendation: 'Urgent cardiology consultation recommended. Early invasive strategy with coronary angiography should be strongly considered. Admit for continuous monitoring and treatment.' } },
  ],
  cha2ds2_vasc: [
    { threshold: 1, guidance: { riskCategory: 'Very Low Risk', interpretation: 'Very low stroke risk (0-0.2% per year)', recommendation: 'No antithrombotic therapy recommended. Annual reassessment of stroke risk factors is advised.' } },
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low stroke risk (0.6-1.3% per year)', recommendation: (score: number, sex?: string) => sex === 'female' && score === 1 ? 'For females with score of 1 (sex alone), no anticoagulation needed. For males with score of 1, consider oral anticoagulation or aspirin based on patient preferences and bleeding risk.' : 'Consider oral anticoagulation or aspirin. Discuss risks and benefits with patient. Assess bleeding risk using HAS-BLED score.' } },
    { threshold: 3, guidance: { riskCategory: 'Low-Moderate Risk', interpretation: 'Low-moderate stroke risk (2.2% per year)', recommendation: 'Oral anticoagulation recommended (direct oral anticoagulant or warfarin). Assess bleeding risk using HAS-BLED score. Benefits typically outweigh risks.' } },
    { threshold: 5, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `Moderate stroke risk (${score === 3 ? '3.2%' : '4.8%'} per year)`, recommendation: 'Oral anticoagulation strongly recommended unless contraindicated. Direct oral anticoagulants (DOACs) are generally preferred over warfarin. Assess bleeding risk using HAS-BLED score.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate-High Risk', interpretation: (score: number) => `Moderate-high stroke risk (${score === 5 ? '6.7%' : '10%'} per year)`, recommendation: 'Oral anticoagulation strongly recommended. DOACs preferred over warfarin in most cases. Careful monitoring and bleeding risk assessment essential.' } },
    { threshold: 10, guidance: { riskCategory: 'High Risk', interpretation: 'High stroke risk (>10% per year)', recommendation: 'Oral anticoagulation essential unless absolute contraindication exists. DOACs preferred. Consider specialist referral for anticoagulation management and close monitoring.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number, sex?: string) => string); recommendation: string | ((score: number, sex?: string) => string) } }[],
  gcs: [
    { threshold: 13, guidance: { riskCategory: 'Mild', interpretation: 'Mild impairment (GCS 13-15). Patient is likely to have good neurological function.', recommendation: 'Mild head injury. Observe for deterioration. Most patients with GCS 13-15 can be managed with observation. Consider CT if mechanism concerning or other high-risk features present.' } },
    { threshold: 9, guidance: { riskCategory: 'Moderate', interpretation: 'Moderate impairment (GCS 9-12). Significant neurological dysfunction present.', recommendation: 'Moderate head injury. Requires hospital admission and close monitoring. CT imaging indicated. Consider neurosurgical consultation. May require ICU admission for frequent neurological assessments.' } },
    { threshold: 0, guidance: { riskCategory: 'Severe', interpretation: (score: number) => `Severe impairment (GCS 3-8). Critical neurological dysfunction. ${score === 3 ? 'GCS 3 is the lowest possible score indicating deep coma.' : ''}`, recommendation: 'Severe head injury. Immediate ICU admission required. Definitive airway management (intubation) strongly recommended for GCS ≤8. Emergency CT imaging and neurosurgical consultation essential. Consider ICP monitoring.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  qsofa: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of sepsis-related mortality and poor outcomes', recommendation: 'qSOFA <2 does not rule out infection or sepsis. Continue clinical assessment. If infection suspected, consider full SOFA score and lactate measurement. Monitor closely for deterioration.' } },
    { threshold: 4, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of sepsis-related mortality (in-hospital mortality ~10% for qSOFA ≥2 vs ~1% for qSOFA <2)', recommendation: 'qSOFA ≥2 suggests sepsis with organ dysfunction. URGENT: Obtain lactate, blood cultures, and complete blood count. Calculate full SOFA score. Initiate sepsis bundle immediately: IV fluids, broad-spectrum antibiotics within 1 hour, and consider ICU admission. Reassess frequently.' } },
  ],
  alvarado: [
    { threshold: 5, guidance: { riskCategory: 'Low Risk', interpretation: 'Low probability of acute appendicitis (5-20% likelihood)', recommendation: 'Appendicitis unlikely. Consider alternative diagnoses. Outpatient management with close follow-up is appropriate. Discharge with return precautions. Re-evaluate if symptoms worsen or persist beyond 24-48 hours.' } },
    { threshold: 7, guidance: { riskCategory: 'Intermediate Risk', interpretation: 'Moderate probability of acute appendicitis (30-65% likelihood)', recommendation: 'Appendicitis possible. Further evaluation recommended with CT scan or ultrasound imaging. Active observation with serial abdominal exams. Consider surgical consultation. Admission for observation may be appropriate if imaging unavailable or equivocal.' } },
    { threshold: 9, guidance: { riskCategory: 'High Risk', interpretation: 'High probability of acute appendicitis (65-85% likelihood)', recommendation: 'Surgical consultation strongly recommended. CT scan or ultrasound can help confirm diagnosis and assess for complications (perforation, abscess). May proceed to surgery based on clinical judgment. NPO (nothing by mouth) and IV hydration. Consider antibiotics.' } },
    { threshold: 11, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high probability of acute appendicitis (>85% likelihood)', recommendation: 'Urgent surgical consultation required. Imaging (CT/ultrasound) recommended but should not significantly delay surgery if patient is clinically unstable. NPO, IV fluids, analgesia, and preoperative antibiotics. Appendectomy is indicated.' } },
  ],
  glasgow_blatchford: [
    { threshold: 1, guidance: { riskCategory: 'Very Low Risk', interpretation: 'Very low risk of requiring intervention. Risk of rebleeding, intervention, or mortality is <1%.', recommendation: 'Patient may be considered for early discharge and outpatient management. No endoscopy required urgently. Ensure adequate follow-up arranged. GBS of 0 has high negative predictive value for needing intervention.' } },
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of requiring intervention. Still consider for potential outpatient management with close follow-up.', recommendation: 'Consider early discharge with outpatient gastroenterology follow-up if clinically stable and no other concerning features. Some patients may benefit from brief observation period.' } },
    { threshold: 6, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of requiring intervention (transfusion, endoscopy, surgery).', recommendation: 'Hospital admission recommended. Arrange upper endoscopy within 24 hours. Type and crossmatch blood. Consider proton pump inhibitor (PPI) infusion. Monitor hemoglobin serially. Gastroenterology consultation advised.' } },
    { threshold: 12, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of requiring urgent intervention. Significant likelihood of need for transfusion, endoscopic or surgical intervention.', recommendation: 'Hospital admission required. Urgent upper endoscopy (within 12-24 hours). IV PPI infusion. Aggressive fluid resuscitation. Type and crossmatch 2-4 units PRBCs. Urgent gastroenterology consultation. Consider ICU admission for close monitoring. NPO status.' } },
    { threshold: 24, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high risk of mortality and need for urgent intervention. Critical upper GI bleeding.', recommendation: 'URGENT: ICU admission. Immediate gastroenterology consultation for urgent upper endoscopy. Large-bore IV access. Aggressive resuscitation with crystalloids and blood products. Transfuse to maintain Hgb >7 g/dL (>8 in cardiovascular disease). High-dose IV PPI. Consider intubation for airway protection if massive hematemesis or altered mental status. Surgery backup may be needed.' } },
  ],
  nihss: [
    { threshold: 1, guidance: { riskCategory: 'No Stroke', interpretation: 'No stroke symptoms detected. Patient appears neurologically intact.', recommendation: 'No acute stroke treatment indicated based on NIHSS alone. Consider other causes of symptoms if clinically suspected stroke. Document baseline NIHSS for future reference.' } },
    { threshold: 5, guidance: { riskCategory: 'Minor Stroke', interpretation: 'Minor stroke (NIHSS 1-4). Small neurological deficit present.', recommendation: 'Consider thrombolytic therapy if within time window and no contraindications (though benefit may be modest for very low scores). Admit to stroke unit. Imaging (CT/MRI) to rule out hemorrhage and confirm ischemia. May be candidate for IV tPA or mechanical thrombectomy based on imaging. Aspirin if not receiving tPA.' } },
    { threshold: 16, guidance: { riskCategory: 'Moderate Stroke', interpretation: 'Moderate stroke (NIHSS 5-15). Significant neurological deficit.', recommendation: 'URGENT: Candidate for thrombolytic therapy (IV tPA) if within 4.5 hours and no contraindications. Consider mechanical thrombectomy if large vessel occlusion and within time window (up to 24 hours for select patients). Immediate CT/MRI to exclude hemorrhage. Neurology and/or stroke team consultation. Admit to stroke unit or ICU. Close monitoring for neurological deterioration.' } },
    { threshold: 21, guidance: { riskCategory: 'Moderate-Severe Stroke', interpretation: 'Moderate to severe stroke (NIHSS 16-20). Major neurological impairment.', recommendation: 'URGENT: High priority for mechanical thrombectomy if large vessel occlusion identified on CT angiography (CTA). IV tPA if eligible and within time window. Immediate neurology/stroke team consultation. ICU admission for close monitoring. High risk for hemorrhagic transformation and cerebral edema. Consider intubation if airway compromise or GCS <8. Neurosurgical consultation may be needed.' } },
    { threshold: 43, guidance: { riskCategory: 'Severe Stroke', interpretation: 'Severe stroke (NIHSS ≥21). Profound neurological deficit. High mortality risk.', recommendation: 'CRITICAL: Emergent mechanical thrombectomy evaluation if large vessel occlusion present. May still benefit from IV tPA if eligible. ICU admission required. Likely need for airway protection/intubation. Risk of malignant cerebral edema is very high - neurosurgical consultation for possible decompressive hemicraniectomy. ICP monitoring may be indicated. Discuss goals of care with family. Multidisciplinary stroke team activation essential.' } },
  ],
  sofa: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of mortality (<10%)', recommendation: 'Continue standard ICU care. Monitor closely for changes in organ function. Reassess SOFA score daily. Focus on treating underlying infection or condition.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `Moderate risk of mortality (${score <= 4 ? '15-20%' : '20-40%'})`, recommendation: 'ICU-level care required. Aggressive treatment of underlying condition. Daily SOFA scoring to track progression. Consider early consultation with specialists for individual organ support (nephrology for renal dysfunction, hepatology for liver dysfunction, etc.). Ensure adequate infection source control.' } },
    { threshold: 12, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of mortality (${score <= 9 ? '40-50%' : '50-75%'})`, recommendation: 'ICU admission essential if not already admitted. Multi-organ support likely needed. Consider mechanical ventilation, renal replacement therapy (CRRT/hemodialysis), vasopressor support as indicated. Daily SOFA scoring critical. Multidisciplinary team approach. Early goals of care discussion with family may be appropriate given high mortality risk.' } },
    { threshold: 25, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high risk of mortality (>80%). Multiple organ dysfunction syndrome (MODS).', recommendation: 'CRITICAL: Maximal ICU support required. Multi-organ failure present. Mechanical ventilation, vasopressor support, and renal replacement therapy likely all needed. Consider ECMO or other advanced therapies if available and appropriate. URGENT goals of care discussion with family essential given very high mortality. Palliative care consultation may be appropriate. Continue aggressive treatment unless family opts for comfort measures.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  perc: [
    { threshold: 1, guidance: { riskCategory: 'PE Ruled Out', interpretation: 'PERC negative (all 8 criteria absent). Risk of PE <1%. PE is effectively ruled out.', recommendation: 'No further workup for PE needed. PERC rule successfully excludes pulmonary embolism. No D-dimer or imaging required. Consider alternative diagnoses for patient symptoms. This rule is designed to safely avoid unnecessary testing in low-risk patients.' } },
    { threshold: 9, guidance: { riskCategory: 'Further Testing Needed', interpretation: (score: number) => `PERC positive (${score} of 8 criteria present). Cannot rule out PE with PERC alone.`, recommendation: 'Proceed with PE workup. Apply Wells PE score for risk stratification. If Wells PE is low, obtain D-dimer; if D-dimer positive or Wells PE is moderate/high, proceed to CT pulmonary angiography (CTPA). PERC rule is meant for rule-out only - when positive, standard PE diagnostic algorithm should be followed.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  timi: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of death, MI, or urgent revascularization at 14 days (4.7%)', recommendation: 'Conservative management appropriate. Early discharge may be considered if troponins negative and patient clinically stable. Outpatient cardiology follow-up recommended. Consider stress testing prior to discharge or as outpatient. Dual antiplatelet therapy and statin recommended.' } },
    { threshold: 3, guidance: { riskCategory: 'Low-Intermediate Risk', interpretation: 'Low-intermediate risk of death, MI, or urgent revascularization at 14 days (8.3%)', recommendation: 'Hospital admission recommended. Serial troponins and ECGs. Early risk stratification with stress testing or coronary CT angiography. Consider early invasive strategy if high-risk features develop. Dual antiplatelet therapy, statin, and anticoagulation as indicated.' } },
    { threshold: 5, guidance: { riskCategory: 'Intermediate Risk', interpretation: (score: number) => `Intermediate risk of death, MI, or urgent revascularization at 14 days (${score === 3 ? '13.2%' : '19.9%'})`, recommendation: 'Hospital admission required. Early invasive strategy should be considered within 24-72 hours. Cardiology consultation recommended. Serial troponins and continuous telemetry monitoring. Dual antiplatelet therapy (aspirin + P2Y12 inhibitor), anticoagulation, high-intensity statin, and beta-blocker. Consider early coronary angiography.' } },
    { threshold: 8, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of death, MI, or urgent revascularization at 14 days (${score === 5 ? '26.2%' : score === 6 ? '40.9%' : '40.9%'})`, recommendation: 'URGENT: Early invasive strategy strongly recommended. Coronary angiography should be performed within 24 hours (or immediately if ongoing ischemia, hemodynamic instability, or electrical instability). ICU or telemetry monitoring required. Aggressive medical therapy: dual antiplatelet therapy, anticoagulation (LMWH, fondaparinux, or UFH), high-intensity statin, beta-blocker. Cardiology consultation essential. Prepare for possible PCI or CABG.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
} as const;
